[package]
name = "sg-name"
version = "0.5.0"
authors = ["Shane Vitarana <s@noreply.publicawsome.com>"]
edition = "2021"
description = "Rust definition of name service metadata, used by Stargaze Names"
license = "Apache-2.0"
repository = "https://github.com/public-awesome/names"
homepage = "https://stargaze.zone"

exclude = [
  # Those files are rust-optimizer artifacts. You might want to commit them for convenience but they should not be part of the source code publication.
  "contract.wasm",
  "hash.txt",
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
cosmwasm-schema = "1.1.4"
schemars = "0.8.8"
serde = { version = "1.0.137", default-features = false, features = ["derive"] }
cosmwasm-std = "1.1.4"
